GET {{host}}

### ------------------------------------ users
### user list
GET {{host}}/users

### create
POST {{host}}/users
Content-Type: application/json

{
  "name": "홍길동10",
  "email": "indiflex10@gmail.com",
  "passwd": "as121adsfa",
  "profile": {
    "photo": "/upload/hong.jpg"
  },
  "addrs": [{
    "street": "서울특별시",
    "detail": "도봉구"
  }],
  "auth": [{"id":4, "type": "X"}]

}

### user - one
GET {{host}}/users/7

### auths - all
GET {{host}}/users/auths

### auths - create
POST {{host}}/users/auths
Content-Type: application/json

{
  "type": "X"
}


###update-user
PATCH {{host}}/users/1
Content-Type: application/json

{
  "name": "홍길동1",
  "email": "indiflex1@gmail.com",
  "passwd": "as121adsfa",
  "profile": {
    "photo": "/upload/hong.jpg",
    "role": 1
  },
  "addrs": [{
    "street": "서울특별시",
    "detail": "도봉구 쌍문동"
  }],
  "auth": [{"type": "W"}]
}

### default-value-pipe
GET {{host}}/users/123x/defpipe

### verify
GET {{host}}/users/verify

### ------------------------------------ services

### redirect
GET {{host}}/redirect-hello?nickname=홍123&addr=서울&age=23

### serviceB test
GET {{host}}/serviceB

###
GET {{host}}/sayHello

###

POST {{host}}
Content-Type: application/json

{
  name: 'xxx'
}
